### ISSUE TITLE
gradle 7?

### ISSUE THREAD

**Issue by guymguym** [awslabs/smithy-rs#1167]
I see that smithy project updated to gradle 7 
https://github.com/awslabs/smithy/pull/1085

When is it going to be updated for smithy-rs?

The reason I "care" is that with gradle 6 I have to manually install jdk 11 (or up to 14) which is quite old.

**Comment by Velfi** [comment]
We agree that this situation isn't ideal but due to internal constraints, we don't plan to address this at this time. As soon as those internal constraints get relaxed or we have a good mitigation we can revisit this issue, but I'm sorry to say that we don't currently have any estimate on when that will be.

**Comment by guymguym** [comment]
Got it, no worries, gradle 6 FTW 😉

**Comment by david-perez** [comment]
We are no longer blocked. We should be able to upgrade to Gradle 7.
