### ISSUE TITLE
[Kinesis customization] Read timeouts

### ISSUE THREAD

**Issue by rcoh** [awslabs/smithy-rs#134]
`GetRecords` requires a read timeout to prevent the HTTP client waiting forever. Medium because controlling read timeouts might be non-trivial

**Comment by jdisanti** [comment]
Attempted to figure out the "why" for this issue. Found that it had a duplicate [in smithy-kotlin that has since been resolved](https://github.com/awslabs/smithy-kotlin/issues/162), and I think it originated from [this Go SDK issue](https://github.com/aws/aws-sdk-go/issues/2971).

My stance on this is that since we're not going to implement a default read timeout, we don't need a customization to modify that default read timeout for Kinesis `GetRecords`.
