### ISSUE TITLE
Is there a plan to make smithy-rs a rust only repo?

### ISSUE THREAD

**Issue by piaoger** [awslabs/smithy-rs#1499]
There are some gradle and kotlin stuffs for building and running.It is quite a different ecosystem for rust development.

**Comment by piaoger** [comment]
Just close it because I don't think the situation can be change in short time :)

**Comment by Velfi** [comment]
Our code generation is written in Kotlin because all of the canonical Smithy tooling is written in Java. This decision to use preexisting tooling allows us to focus on producing the SDKs and frees us from having to maintain that tooling.

We currently have no plans to change this.

If you're interested in contributing to the SDK but are finding it difficult to get started, please let us know. We very much appreciate external contributions, and we want to support those contributors as best we can.

**Comment by rcoh** [comment]
We do have a medium term plan to dockerize the code generator to make it easier to run, if that would be helpful to you please let us know!
