### ISSUE TITLE
How do I properly configure ECS credentials using aws_config?

### ISSUE THREAD

**Issue by 77sa** [awslabs/smithy-rs#1614]
Sorry if this is not the right place to ask. I was lead here from https://docs.rs/aws-config/latest/aws_config/ecs/index.html.

I'm trying to configure ECS credentials with IAM role I have set up on a task (which I will then use to create a DynamoDB client).
Heres my code:
```rust
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let config;
    let ddb;
    match env::var("ECS") {
        Ok(_) => {
            // Get credentials and build config
            let credentials =
                aws_config::ecs::EcsCredentialsProvider::builder()
                    .build()
                    .credentials()
                    .await
                    .unwrap();
            let config = Config::builder()
                .credentials_provider(credentials)
                .region(Region::new("eu-west-2"))
                .build();
            ddb = DDBClient::from_conf(config);
        }
        Err(_) => {
            // Load from environment variables
            config = aws_config::load_from_env().await;
            ddb = DDBClient::new(&config);
        }
    }
    // ...
}
```

When I deploy this to ECS I get an error on the credentials unwrap:
```shell
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CredentialsNotLoaded { context: "ECS provider not configured" }', src/main.rs:19:22
```

I've also tried using it with ```ProviderConfig``` and passing that into the credential provider builder through ```.configure(&p_config)``` which results in the same error.

I'm guessing I'm missing something here. If anyone could shoot me an example of how to configure it properly I would be grateful.

**Comment by jdisanti** [comment]
The error you're saying is indicating there are no ECS credentials, and it is used to notify the default credential provider chain to move on to the next provider.

However, the default credentials provider chain already includes the `EcsCredentialsProvider`, so you shouldn't need this switching logic to begin with.

Just as a note: you generally don't want to pull the credentials directly from the provider and pass them in, since that will prevent the client from making any successful calls after a certain amount of time (when the credentials expire). Generally, you want to give the whole provider to the client configuration so that it can automatically refresh.
