### ISSUE TITLE
Convert time extension not working for non-smithy crates

### ISSUE THREAD

**Issue by allan2** [awslabs/smithy-rs#1688]
`DateTimeExt` works for `aws_smithy_types` but not for other crates like EC2.

```rust
use aws_smithy_types_convert::date_time::DateTimeExt;
use chrono::Utc;
use std::{convert::TryFrom, time::SystemTime};

fn main() {
    aws_smithy_types::date_time::DateTime::from_secs(5).to_chrono_utc(); // works

    let ec2_time = aws_sdk_ec2::types::DateTime::from_secs(5);
    ec2_time.to_chrono_utc(); // doesn't work;no method found

    // works
    let sys_time = SystemTime::try_from(ec2_time).unwrap();
    let chrono_time = chrono::DateTime::<Utc>::from(sys_time);
}
```

Minimum working example repo here --> https://github.com/allan2/aws-convert-time

**Comment by jdisanti** [comment]
I think this should work for you if you change the 0.48 versions to 0.47 to be consistent with what the EC2 crate is depending on:
```
aws-smithy-types-convert = { version = "0.47", features = ["convert-chrono"] }
aws-smithy-types = "0.47"
aws-sdk-ec2 = "0.17"
```

**Comment by allan2** [comment]
Thanks John. That works.

Is there any way to show a warning when versions are mismatched?

**Comment by jdisanti** [comment]
> Is there any way to show a warning when versions are mismatched?

Not an easy way that I'm aware of, unfortunately. You can setup [`cargo-deny`](https://crates.io/crates/cargo-deny) to disallow or warn on duplicate dependencies, but it will likely complain about many other transitive dependencies as well.

I think this is a problem that will go away once we reach 1.0 since we'll have stability guarantees among all these crates. Until then, the [`versions.toml`](https://github.com/awslabs/aws-sdk-rust/blob/main/versions.toml) file in aws-sdk-rust tracks which versions pair together for any given release (for a specific release, look at that file at the release tag).
