### ISSUE TITLE
[Python] Improve streaming Blob testing suite

### ISSUE THREAD

**Issue by crisidev** [awslabs/smithy-rs#2115]
The `Blob` tests are far from ideal. They do not work with asyncio is involved and it seems like during tests the `Blob` is loaded in memory and not really streamed, while when running on a real application the streaming feature seems to be working properly.

https://github.com/awslabs/smithy-rs/blob/main/rust-runtime/aws-smithy-http-server-python/src/types.rs#L499

**Comment by unexge** [comment]
I believe this is addressed with https://github.com/awslabs/smithy-rs/pull/2431. I didn't pay attention to the issue about loading the whole content to the memory, but it seems like [the test](https://github.com/awslabs/smithy-rs/blob/26cb37afb0087d1dee401fafc907c112233bbaaa/rust-runtime/aws-smithy-http-server-python/src/types.rs#L640-L658) is problematic (I think we should use [`stream::repeat`](https://docs.rs/futures/latest/futures/stream/fn.repeat.html) instead of `String::repeat`). I'll close this ticket, but we can revisit that problem as part of https://github.com/awslabs/smithy-rs/issues/1752
