### ISSUE TITLE
Update `aws_smithy_types::date_time::Format::HttpDate` to omit fractional seconds

### ISSUE THREAD

**Issue by Velfi** [awslabs/smithy-rs#2831]
Per https://github.com/awslabs/smithy/pull/1847, we need to update [`aws_smithy_types::date_time::Format::HttpDate`](https://docs.rs/aws-smithy-types/latest/aws_smithy_types/date_time/enum.Format.html#variant.HttpDate) to omit fractional seconds.

**Comment by rschmitt** [comment]
This was marked as a good first issue? This strikes me as potentially very complicated, in terms of its implications.

**Comment by rcoh** [comment]
I think the implications are outside of our control here. We need to update the date time serializer to remove the fractional part because services are currently _rejecting_ requests when they have them. If more subtle behavior is required, then we need an update to the Smithy spec.

The implementation itself seems straightforward enough since it's just deleting https://github.com/awslabs/smithy-rs/blob/main/rust-runtime/aws-smithy-types/src/date_time/format.rs#L482 I think?

**Comment by rschmitt** [comment]
Ok, makes sense.
