### ISSUE TITLE
Update Region builders for configs to be consistent with the type signatures of the RetryConfig builders

### ISSUE THREAD

**Issue by Velfi** [awslabs/smithy-rs#748]
*these APIs are defined in `aws/rust-runtime/aws-types/config.rs`*
Currently, the `retry_config` builders have these signatures:

```rust
pub fn retry_config(mut self, retry_config: RetryConfig) -> Self;
pub fn set_retry_config(&mut self, retry_config: Option<RetryConfig>) -> &mut Self;
```

but the `region` builders have these signatures:

```rust
pub fn region(mut self, region: impl Into<Option<Region>>) -> Self;
pub fn set_region(&mut self, region: impl Into<Option<Region>>) -> &mut Self;
```

The region builder API should be updated to match the retry_config builder API.

**Comment by rcoh** [comment]
This is like this to support setting region from the output of a region provider (but also from a hard coded region).

Since a region provider returns `Option<Region>` by accepting `into<Option<Region>>` we can handle both region and option region from the same signature. But since aws-types/config.rs is rarely used directly at this point, it's possible this could be refactored without impairing ergonomics.
